CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (
        role IN ('HOD', 'FACULTY', 'STUDENT')
    ),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    branch TEXT NOT NULL,
    year INTEGER NOT NULL,
    section TEXT NOT NULL,
    user_id INTEGER UNIQUE,
    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE TABLE faculty (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    user_id INTEGER UNIQUE,
    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE TABLE subjects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code TEXT NOT NULL UNIQUE,
    subject_name TEXT NOT NULL,
    faculty_id INTEGER NOT NULL,
    year INTEGER NOT NULL,
    section TEXT NOT NULL,
    FOREIGN KEY (faculty_id)
        REFERENCES faculty(id)
        ON DELETE CASCADE
);

CREATE TABLE attendance_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id INTEGER NOT NULL,
    faculty_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    period INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (subject_id)
        REFERENCES subjects(id)
        ON DELETE CASCADE,

    FOREIGN KEY (faculty_id)
        REFERENCES faculty(id)
        ON DELETE CASCADE,

    UNIQUE(subject_id, date, period)
);

CREATE TABLE attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    period TEXT NOT NULL,

    status TEXT NOT NULL
        CHECK(status IN ('PRESENT', 'ABSENT')),

    marked_by INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (student_id)
        REFERENCES students(id),

    FOREIGN KEY (subject_id)
        REFERENCES subjects(id),

    FOREIGN KEY (marked_by)
        REFERENCES faculty(id),

    UNIQUE (
        student_id,
        subject_id,
        date,
        period
    )
);